# Generated by Django 2.2.2 on 2020-01-05 19:36

import apps.documents.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_no', models.UUIDField(default=uuid.uuid4, verbose_name='Document Number')),
                ('terms', models.TextField(blank=True, default='')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('description', models.TextField(blank=True, default='')),
                ('document_path', models.FileField(upload_to=apps.documents.models.document_path, verbose_name='documents')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_clients', to='users.Profile', verbose_name='Document Client ')),
            ],
        ),
    ]
