# Generated by Django 2.2.2 on 2020-01-05 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=128, verbose_name='Company')),
                ('server_url', models.URLField(null=True, verbose_name='Server url')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='with country code (eg. +48)', max_length=128, null=True, region=None, verbose_name='Mobile')),
                ('country', models.CharField(default='Germany', max_length=64, verbose_name='Country')),
                ('city', models.CharField(default='Düsseldorf', max_length=64, verbose_name='city')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
